services:
  redis-node-1:
    image: redis:6.2
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip redis-node-1
    ports:
      - "7001:6379"
    volumes:
      - redis-data-node-1:/data
    networks:
      - redis-cluster

  redis-node-2:
    image: redis:6.2
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip redis-node-2
    ports:
      - "7002:6379"
    volumes:
      - redis-data-node-2:/data
    networks:
      - redis-cluster

  redis-node-3:
    image: redis:6.2
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes --cluster-announce-ip redis-node-3
    ports:
      - "7003:6379"
    volumes:
      - redis-data-node-3:/data
    networks:
      - redis-cluster

networks:
  redis-cluster:
    driver: bridge

volumes:
  redis-data-node-1:
  redis-data-node-2:
  redis-data-node-3:
