services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A worker worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis